#!/usr/bin/env node
// Builds the STM32 web assets header: lib/WIFI_STM32/web-stm32-info.h
// Reads stm32-info.html and stm32-update.html, gzips with Zopfli, emits a C header.
// Run from the html/ directory: node build-stm32.js
//
// Output: ../lib/WIFI_STM32/web-stm32-info.h
// Included by lib/WIFI_STM32/WebPage.h

import { readFileSync, writeFileSync } from 'fs';
import Zopfli from 'node-zopfli-es';
import path from 'path';
import { fileURLToPath } from 'url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));

function toCId(name) {
  let id = name.replace(/[^a-zA-Z0-9]/g, '_');
  if (/^[0-9]/.test(id)) id = '_' + id;
  return id;
}

function toHexLines(buf) {
  const parts = [];
  for (let i = 0; i < buf.length; i++) {
    parts.push('0x' + buf[i].toString(16).padStart(2, '0'));
  }
  const lines = [];
  for (let i = 0; i < parts.length; i += 16) {
    lines.push('  ' + parts.slice(i, i + 16).join(', '));
  }
  return lines.join(',\n');
}

const assets = [
  { webPath: '/index.html',  srcFile: 'stm32-info.html',   contentType: 'text/html' },
  { webPath: '/update.html', srcFile: 'stm32-update.html', contentType: 'text/html' },
];

let header = `#pragma once
#include <stddef.h>
#include <stdint.h>

// STM32 web assets - gzip compressed, served with Content-Encoding: gzip
// Generated by html/build-stm32.js - run \`npm run build:stm32\` from html/ to regenerate.
// Do not edit manually.
//
// Included by lib/WIFI_STM32/WebPage.h which provides the WebAsset typedef.

`;

const entries = [];

for (const asset of assets) {
  const srcPath = path.join(__dirname, asset.srcFile);
  const src = readFileSync(srcPath);
  const compressed = Zopfli.gzipSync(src, { numiterations: 15 });
  const id = toCId(asset.webPath.replace(/^\//, ''));
  header += `// ${asset.webPath} (original ${src.length} bytes) -> compressed ${compressed.length} bytes\n`;
  header += `static const unsigned char ${id}[] = {\n${toHexLines(compressed)}\n};\n`;
  header += `static const size_t ${id}_len = ${compressed.length};\n\n`;
  entries.push({ webPath: asset.webPath, id, contentType: asset.contentType });
}

header += `// Asset index - iterated by ST67WifiOtaMode::serveAsset()\n`;
header += `static const WebAsset WEB_ASSETS[] = {\n`;
for (const e of entries) {
  header += `  { "${e.webPath}", "${e.contentType}", ${e.id}, ${e.id}_len },\n`;
}
header += `};\n`;
header += `static const size_t WEB_ASSETS_COUNT = sizeof(WEB_ASSETS) / sizeof(WEB_ASSETS[0]);\n`;

const outFile = path.join(__dirname, '..', 'lib', 'WIFI_STM32', 'web-stm32-info.h');
writeFileSync(outFile, header, 'utf8');
const totalCompressed = entries.reduce((sum, e) => {
  const id = e.id;
  const match = header.match(new RegExp(`${id}\\[\\] = \\{[\\s\\S]*?\\};\nstatic const size_t ${id}_len = (\\d+);`));
  return sum + (match ? parseInt(match[1]) : 0);
}, 0);
console.log(`Written ${path.relative(process.cwd(), outFile)} with ${entries.length} assets`);
for (const e of entries) {
  console.log(`  ${e.webPath}`);
}
