#!/usr/bin/env python3
"""
Builds the STM32 web assets header: ../lib/WIFI_STM32/web-stm32-info.h
Reads stm32-info.html and stm32-update.html, gzips them, emits a C header.

Run from html/ directory: python3 build-stm32.py
Or via npm:               npm run build:stm32
"""

import gzip
import os
import sys

SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
OUT_FILE = os.path.join(SCRIPT_DIR, '..', 'lib', 'WIFI_STM32', 'web-stm32-info.h')

ASSETS = [
    ('/index.html',   'stm32-info.html',    'text/html'),
    ('/binding.html', 'stm32-binding.html', 'text/html'),
    ('/update.html',  'stm32-update.html',  'text/html'),
]


def to_c_id(web_path):
    name = web_path.lstrip('/')
    return ''.join(c if c.isalnum() else '_' for c in name)


def to_hex_lines(data):
    parts = ['0x{:02x}'.format(b) for b in data]
    lines = []
    for i in range(0, len(parts), 16):
        lines.append('  ' + ', '.join(parts[i:i+16]))
    return ',\n'.join(lines)


def gzip_compress(data):
    import io
    buf = io.BytesIO()
    # Use compresslevel=9 (best compression, standard gzip)
    with gzip.GzipFile(fileobj=buf, mode='wb', compresslevel=9, mtime=0) as f:
        f.write(data)
    return buf.getvalue()


header = """\
#pragma once
#include <stddef.h>
#include <stdint.h>

// STM32 web assets - gzip compressed, served with Content-Encoding: gzip
// Generated by html/build-stm32.py - run `python3 build-stm32.py` from html/ to regenerate.
// Do not edit manually.
//
// Included by lib/WIFI_STM32/WebPage.h which provides the WebAsset typedef.

"""

entries = []

for web_path, src_file, content_type in ASSETS:
    src_path = os.path.join(SCRIPT_DIR, src_file)
    with open(src_path, 'rb') as f:
        src_data = f.read()
    compressed = gzip_compress(src_data)
    c_id = to_c_id(web_path)
    header += f'// {web_path} (original {len(src_data)} bytes) -> compressed {len(compressed)} bytes\n'
    header += f'static const unsigned char {c_id}[] = {{\n{to_hex_lines(compressed)}\n}};\n'
    header += f'static const size_t {c_id}_len = {len(compressed)};\n\n'
    entries.append((web_path, c_id, content_type, len(src_data), len(compressed)))

header += '// Asset index - iterated by ST67WifiOtaMode::serveAsset()\n'
header += 'static const WebAsset WEB_ASSETS[] = {\n'
for web_path, c_id, content_type, _, _ in entries:
    header += f'  {{ "{web_path}", "{content_type}", {c_id}, {c_id}_len }},\n'
header += '};\n'
header += 'static const size_t WEB_ASSETS_COUNT = sizeof(WEB_ASSETS) / sizeof(WEB_ASSETS[0]);\n'

out_path = os.path.normpath(OUT_FILE)
with open(out_path, 'w') as f:
    f.write(header)

print(f'Written {os.path.relpath(out_path)} with {len(entries)} assets:')
for web_path, _, _, raw, comp in entries:
    print(f'  {web_path}  ({raw} -> {comp} bytes, {100*comp//raw}% of original)')
