#if defined(TARGET_RX)

#include "SerialMavlink.h"
#include "CRSFRouter.h"
#include "common.h"
#include "config.h"
#include "device.h"
#include "rx_mavlink.h"

#define MAVLINK_RC_PACKET_INTERVAL 10

#define MAVLINK_COMM_NUM_BUFFERS 1
#include "common/mavlink.h"
#include "MavFrame.h"

#define MAV_FTP_OPCODE_OPENFILERO 4

SerialMavlink::SerialMavlink(Stream &out, Stream &in):
    SerialIO(&out, &in),
    
    //system ID of the device component sending command to FC, can be set using lua options, 0 is the default value for initialized storage, treat it as 255 which is commonly used as GCS SysID
    this_system_id(config.GetSourceSysId() ? config.GetSourceSysId() : 255),
    //use telemetry radio compId as we are providing radio status messages and pass telemetry
    this_component_id(MAV_COMPONENT::MAV_COMP_ID_TELEMETRY_RADIO),

    // system ID of vehicle we want to control must be the same as target vehicle, can be set using lua options, 0 is the default value for initialized storage, treat it as 1 which is commonly used as UAV SysID in 1:1 networks
    target_system_id(config.GetTargetSysId() ? config.GetTargetSysId() : 1),
    // Send to all components as we may have ex. gimbal that listens to RC instead of using Autopilot driver
    target_component_id(MAV_COMPONENT::MAV_COMP_ID_ALL)
{
    RxMavlink_Attach(&mavlinkInputBuffer, &fcFrameLen);
}

SerialMavlink::~SerialMavlink()
{
    RxMavlink_Detach();
}

uint32_t SerialMavlink::sendRCFrame(bool frameAvailable, bool frameMissed, uint32_t *channelData)
{
    if (!frameAvailable) {
        return DURATION_IMMEDIATELY;
    }

    const mavlink_rc_channels_override_t rc_override {
        chan1_raw: CRSF_to_US(channelData[0]),
        chan2_raw: CRSF_to_US(channelData[1]),
        chan3_raw: CRSF_to_US(channelData[2]),
        chan4_raw: CRSF_to_US(channelData[3]),
        chan5_raw: CRSF_to_US(channelData[4]),
        chan6_raw: CRSF_to_US(channelData[5]),
        chan7_raw: CRSF_to_US(channelData[6]),
        chan8_raw: CRSF_to_US(channelData[7]),
        target_system: target_system_id,
        target_component: target_component_id,
        chan9_raw: CRSF_to_US(channelData[8]),
        chan10_raw: CRSF_to_US(channelData[9]),
        chan11_raw: CRSF_to_US(channelData[10]),
        chan12_raw: CRSF_to_US(channelData[11]),
        chan13_raw: CRSF_to_US(channelData[12]),
        chan14_raw: CRSF_to_US(channelData[13]),
        chan15_raw: CRSF_to_US(channelData[14]),
        chan16_raw: CRSF_to_US(channelData[15]),
    };

    uint8_t buf[MAVLINK_MSG_ID_RC_CHANNELS_OVERRIDE_LEN + MAVLINK_NUM_NON_PAYLOAD_BYTES];
    mavlink_message_t msg;
    mavlink_msg_rc_channels_override_encode(this_system_id, this_component_id, &msg, &rc_override);
    uint16_t len = mavlink_msg_to_send_buffer(buf, &msg);
    _outputPort->write(buf, len);
    
    return MAVLINK_RC_PACKET_INTERVAL;
}

int SerialMavlink::getMaxSerialReadSize()
{
    // A partly received frame is held outside the queue: leave room for it, so every frame that
    // completes fits. What isn't read waits in the UART.
    const uint16_t free = mavlinkInputBuffer.free();
    return free > fcFrameLen ? free - fcFrameLen : 0;
}

void SerialMavlink::processBytes(uint8_t *bytes, u_int16_t size)
{
    // Only queue whole frames from the FC, so frames generated by the receiver can be
    // queued in between without corrupting the stream. Frames are not CRC checked as
    // they may be from a dialect we do not know the CRC extras for.
    for (uint16_t i = 0; i < size; i++)
    {
        const uint8_t c = bytes[i];
        if (fcFrameLen == 0 && c != MAVLINK_STX && c != MAVLINK_STX_MAVLINK1)
        {
            continue; // Wait for the start of a frame
        }
        fcFrame[fcFrameLen++] = c;

        if (fcFrameLen == 3)
        {
            // Have STX, LEN and (for v2) the incompat flags, so the frame length is known
            if (fcFrame[0] == MAVLINK_STX_MAVLINK1)
            {
                fcFrameExpectedLen = MAVLINK_CORE_HEADER_MAVLINK1_LEN + 1 + fcFrame[1] + MAVLINK_NUM_CHECKSUM_BYTES;
            }
            else
            {
                fcFrameExpectedLen = MAVLINK_CORE_HEADER_LEN + 1 + fcFrame[1] + MAVLINK_NUM_CHECKSUM_BYTES
                    + ((c & MAVLINK_IFLAG_SIGNED) ? MAVLINK_SIGNATURE_BLOCK_LEN : 0);
            }
        }
        else if (fcFrameLen > 3 && fcFrameLen == fcFrameExpectedLen)
        {
            if (connectionState == connected && mavlinkInputBuffer.free() >= fcFrameLen)
            {
                mavlinkInputBuffer.atomicPushBytes(fcFrame, fcFrameLen);
            }
            learnFromFcFrame();
            fcFrameLen = 0;
        }
    }
}

void SerialMavlink::learnFromFcFrame()
{
    // The vehicle's system ID comes from its HEARTBEAT (message ID 0), the only frames decoded here
    const uint32_t msgid = fcFrame[0] == MAVLINK_STX_MAVLINK1
        ? fcFrame[5]
        : fcFrame[7] | (fcFrame[8] << 8) | ((uint32_t)fcFrame[9] << 16);
    if (msgid != MAVLINK_MSG_ID_HEARTBEAT)
        return;
    mavlink_message_t buffer;
    mavlink_status_t bufferStatus = {};
    for (uint16_t i = 0; i < fcFrameLen; i++)
    {
        mavlink_message_t msg;
        mavlink_status_t status;
        if (mavlink_frame_char_buffer(&buffer, &bufferStatus, fcFrame[i], &msg, &status) == MAVLINK_FRAMING_OK)
        {
            RxMavlink_HandleVehicle(&msg);
        }
    }
}

void SerialMavlink::sendQueuedData(uint32_t maxBytesToSend)
{

    // Send radio messages at 100Hz
    const uint32_t now = millis();
    if ((now - lastSentFlowCtrl) > 10)
    {
        lastSentFlowCtrl = now; 

        // Software-based flow control for mavlink
        uint8_t percentage_remaining = ((MAV_INPUT_BUF_LEN - mavlinkInputBuffer.size()) * 100) / MAV_INPUT_BUF_LEN;

        // Populate radio status packet
        const mavlink_radio_status_t radio_status {
            rxerrors: 0,
            fixed: 0,
            rssi: (uint8_t)((float)linkStats.uplink_Link_quality * 2.55),
            remrssi: linkStats.uplink_RSSI_1,
            txbuf: percentage_remaining,
            noise: (uint8_t)linkStats.uplink_SNR,
            remnoise: 0,
        };

        uint8_t buf[MAVLINK_MSG_ID_RADIO_STATUS_LEN + MAVLINK_NUM_NON_PAYLOAD_BYTES];
        mavlink_message_t msg;
        mavlink_msg_radio_status_encode(this_system_id, this_component_id, &msg, &radio_status);
        uint16_t len = mavlink_msg_to_send_buffer(buf, &msg);
        _outputPort->write(buf, len);
    }

    RxMavlink_Tick(now, connectionState == connected);

    auto size = mavlinkOutputBuffer.size();
    if (size == 0)
    {
        // nothing to send
        return;
    }

    uint8_t apBuf[size];
    mavlinkOutputBuffer.lock();
    mavlinkOutputBuffer.popBytes(apBuf, size);
    mavlinkOutputBuffer.unlock();

    for (uint16_t i = 0; i < size; ++i)
    {
        uint8_t c = apBuf[i];

        mavlink_message_t msg;
        mavlink_status_t status;

        // Try parse a mavlink message
        const uint8_t result = mavlink_frame_char(MAVLINK_COMM_0, c, &msg, &status);
        if (result)
        {
            // Message decoded successfully

            // Only a frame with a valid CRC can be decoded for the receiver
            if (result == MAVLINK_FRAMING_OK)
            {
                RxMavlink_HandleGcs(&msg, now);
                if (RxMavlink_IsAddressedToRx(&msg))
                {
                    continue;
                }
            }

            // Written as received, not re-serialised: mavlink_msg_to_send_buffer() trims an untrimmed
            // MAVLink 2 frame but keeps its checksum, so the FC would reject it
            uint8_t header[MAVLINK_NUM_HEADER_BYTES];
            _outputPort->write(header, mavFrameHeader(&msg, header));
            _outputPort->write((const uint8_t *)_MAV_PAYLOAD(&msg), msg.len);
            _outputPort->write(msg.ck, MAVLINK_NUM_CHECKSUM_BYTES);
            _outputPort->write(msg.signature, mavFrameSignatureLen(&msg));
        }
    }
}

void SerialMavlink::event()
{
    this_system_id = config.GetSourceSysId() ? config.GetSourceSysId() : 255;
    target_system_id = config.GetTargetSysId() ? config.GetTargetSysId() : 1;
}

void SerialMavlink::forwardMessage(const uint8_t *data)
{
    mavlinkOutputBuffer.atomicPushBytes(data + 2, data[1]);
}

bool SerialMavlink::GetNextPayload(uint8_t* nextPayloadSize, uint8_t *payloadData)
{
    if (mavlinkInputBuffer.size() == 0)
    {
        return false;
    }
    const uint16_t count = std::min(mavlinkInputBuffer.size(), (uint16_t)CRSF_PAYLOAD_SIZE_MAX); // Constrain to CRSF max payload size to match SS
    payloadData[0] = CRSF_ADDRESS_USB; // device_addr - used on TX to differentiate between std tlm and mavlink
    payloadData[1] = count;
    // The following 'n' bytes are just raw mavlink
    mavlinkInputBuffer.popBytes(payloadData + CRSF_FRAME_NOT_COUNTED_BYTES, count);
    RxMavlink_DownlinkPopped(count);
    *nextPayloadSize = count + CRSF_FRAME_NOT_COUNTED_BYTES;
    return true;
}

#endif // defined(TARGET_RX)
