#include "tx_mavlink.h"

#include "common.h"
#include "config.h"
#include "CRSFRouter.h"
#include "FHSS.h"
#include "deferred.h"
#include "handset.h"
#include "logging.h"
#include "options.h"
#include "OTA.h"
#include "POWERMGNT.h"
#include "TXModuleEndpoint.h"

#include "MavParamServer.h"
#include "common/mavlink.h"
// storm32 dialect messages; their headers stand alone next to common
#include "storm32/mavlink_msg_mlrs_radio_link_information.h"
#include "storm32/mavlink_msg_mlrs_radio_link_stats.h"

#if defined(PLATFORM_STM32)
#include "mavlink_udp.h"
#endif

// Rate and band changes are applied by a deferred function, so wait before reading them back
#define PARAM_REPLY_DELAY 100
// A link mode change ends the GCS session, so it is applied after the reply has gone out
#define LINK_MODE_APPLY_DELAY 300
// No heartbeat for this long after start unless the vehicle is seen, then sysid 1 (bench setups)
#define HEARTBEAT_WAIT 5000
// A frame from the vehicle that has not completed by now was cut short by the link dropping
#define DOWNLINK_FRAME_TIMEOUT 500
// Also sent as soon as it changes
#define LINK_INFORMATION_INTERVAL 5000

// storm32.xml enums, which the generated headers don't define
#define MLRS_FLAG_RSSI_DBM 1
#define MLRS_FLAG_RX_RECEIVE_ANTENNA2 2
#define MLRS_FLAG_TX_TRANSMIT_ANTENNA1 32
#define MLRS_FLAG_TX_TRANSMIT_ANTENNA2 64
#define MLRS_LINK_TYPE_EXPRESSLRS 5

#define HAS_RADIO (GPIO_PIN_SCK != UNDEF_PIN)

extern Stream *TxUSB;
#if defined(PLATFORM_ESP32)
extern bool BackpackTelemReadyToSend;
#endif

static MavParamServer server;
static bool started;

static mavlink_message_t gcsRxMsg[GCS_LINK_COUNT];
static mavlink_status_t gcsRxStatus[GCS_LINK_COUNT];
static mavlink_message_t vehicleRxMsg;
static mavlink_status_t vehicleRxStatus;
static uint32_t lastVehicleByte;

// Frames generated by the TX, held until the stream from the vehicle is between frames
static uint8_t queuedFrames[MAVLINK_MAX_PACKET_LEN * 2];
static uint16_t queuedLen;

static const uint16_t powerLevelsMw[PWR_COUNT] = {10, 25, 50, 100, 250, 500, 1000, 2000};

// -1 for none
static int8_t pendingLinkMode = -1;

static bool isWhole(float value, float max)
{
    return value >= 0 && value <= max && value == (float)(uint16_t)value;
}

// The doc comments on each entry are read by python/gen_param_metadata.py

static float getPacketRate() { return get_elrs_airRateConfig(config.GetRate())->enum_rate; }
static const char *setPacketRate(float value)
{
    if (!isWhole(value, 255))
        return "not a packet rate";
    for (uint8_t index = 0; index < RATE_MAX; index++)
    {
        const expresslrs_mod_settings_s *modParams = get_elrs_airRateConfig(index);
        if (modParams->enum_rate != (uint8_t)value)
            continue;
        if (!isSupportedRFRate(index))
            break;
        // The same rates the Lua offers
        if (modParams->interval * modParams->numOfSends < handset->getMinPacketInterval())
            return "too fast for the handset link";
        crsfTransmitter.SetPacketRateIdx(index, true);
        return nullptr;
    }
    return "not supported on this hardware";
}

// From the configured rate, which the radio switches to once the sync packets announcing it are out
static float getPacketHz()
{
    const int32_t interval = get_elrs_airRateConfig(config.GetRate())->interval;
    return (1000000 + interval / 2) / interval;
}

static float getTlmRatio() { return config.GetTlm(); }
static const char *lockTlmRatio() { return crsfTransmitter.TlmRatioLockReason(); }
static const char *setTlmRatio(float value)
{
    if (!isWhole(value, TLM_RATIO_DISARMED))
        return "not a ratio";
    crsfTransmitter.SetTlmRatio((uint8_t)value);
    return nullptr;
}

static bool hasSwitchMode() { return !firmwareOptions.is_airport; }
static float getSwitchMode() { return config.GetSwitchMode(); }
static const char *lockSwitchMode() { return crsfTransmitter.SwitchModeLockReason(); }
static const char *setSwitchMode(float value)
{
    if (!isWhole(value, OtaIsFullRes ? 2 : 1))
        return "not a mode at this rate";
    crsfTransmitter.SetSwitchMode((uint8_t)value);
    return nullptr;
}

static bool hasAntennaMode() { return isDualRadio(); }
static float getAntennaMode() { return config.GetAntennaMode(); }
static const char *setAntennaMode(float value)
{
    if (!isWhole(value, TX_RADIO_MODE_SWITCH))
        return "not an antenna mode";
    if (get_elrs_airRateConfig(config.GetRate())->radio_type == RADIO_TYPE_LR1121_LORA_DUAL && value != TX_RADIO_MODE_GEMINI)
        return "dual band rates use Gemini";
    crsfTransmitter.SetAntennaMode((uint8_t)value);
    return nullptr;
}

static float getLinkMode() { return pendingLinkMode >= 0 ? pendingLinkMode : config.GetLinkMode(); }
static const char *setLinkMode(float value)
{
    if (!isWhole(value, TX_MAVLINK_MODE))
        return "not a link mode";
    if (value == getLinkMode())
        return nullptr;
    // Leaving MAVLink keeps the switch mode, so the RX can follow from the sync packet while linked
    pendingLinkMode = (int8_t)value;
    deferExecutionMillis(LINK_MODE_APPLY_DELAY, []() {
        config.SetLinkMode(pendingLinkMode);
        pendingLinkMode = -1;
    });
    return nullptr;
}

static bool hasRadio() { return HAS_RADIO; }
static float getPower() { return powerLevelsMw[config.GetPower()]; }
static const char *setPower(float value)
{
    for (uint8_t power = POWERMGNT::getMinPower(); power <= POWERMGNT::getMaxPower(); power++)
    {
        if (value == powerLevelsMw[power])
        {
            crsfTransmitter.SetPowerMax(power);
            return nullptr;
        }
    }
    return "not a power level of this TX";
}

static float getDynamicPower() { return config.GetDynamicPower() ? config.GetBoostChannel() + 1 : 0; }
static const char *setDynamicPower(float value)
{
    if (!isWhole(value, 5))
        return "not a dynamic power mode";
    crsfTransmitter.SetDynamicPower((uint8_t)value);
    return nullptr;
}

static bool hasFan() { return GPIO_PIN_FAN_EN != UNDEF_PIN || GPIO_PIN_FAN_PWM != UNDEF_PIN; }
static float getFanThreshold() { return config.GetPowerFanThreshold(); }
static const char *setFanThreshold(float value)
{
    if (!isWhole(value, PWR_COUNT))
        return "not a threshold";
    config.SetPowerFanThreshold((uint8_t)value);
    return nullptr;
}

#if defined(PLATFORM_ESP32)
static bool hasBackpack() { return OPT_USE_TX_BACKPACK && !config.GetBackpackDisable(); }
static float getBackpackTelemetry() { return config.GetBackpackTlmMode(); }
static const char *setBackpackTelemetry(float value)
{
    if (!isWhole(value, BACKPACK_TELEM_MODE_WIFI))
        return "not a telemetry mode";
    config.SetBackpackTlmMode((uint8_t)value);
    BackpackTelemReadyToSend = true;
    return nullptr;
}
#endif

static float getVehicleSysid() { return server.vehicleSysid(); }

static const MavParam params[] = {
    // @Param: TX_PKT_RATE
    // @DisplayName: Packet rate
    // @Description: Over-the-air packet rate and modulation, as the ExpressLRS rate number (the same on all hardware). The number also selects the band: 0-19 sub-GHz, 20-39 2.4 GHz, 100+ dual band. Rates this TX or the handset link cannot run are refused. The link re-syncs to the new rate.
    // @Values: 0:25Hz (900),1:50Hz (900),2:100Hz (900),3:100Hz Full (900),4:150Hz (900),5:200Hz (900),6:200Hz Full (900),7:250Hz (900),8:333Hz Full (900),9:500Hz (900),10:D50Hz (900),11:K1000 Full (900),20:25Hz (2.4),21:50Hz (2.4),22:100Hz (2.4),23:100Hz Full (2.4),24:150Hz (2.4),25:200Hz (2.4),26:200Hz Full (2.4),27:250Hz (2.4),28:333Hz Full (2.4),29:500Hz (2.4),30:D250 (2.4),31:D500 (2.4),32:F500 (2.4),33:F1000 (2.4),34:DK250 (2.4),35:DK500 (2.4),36:K1000 (2.4),100:100Hz Full (X-Band),101:150Hz (X-Band)
    // @Hardware: Each TX supports a subset; see TX_PKT_HZ for the rate in Hz
    // @User: Standard
    {"TX_PKT_RATE", hasRadio, getPacketRate, setPacketRate, nullptr},
    // @Param: TX_PKT_HZ
    // @DisplayName: Packet rate (Hz)
    // @Description: Over-the-air packets per second at the current packet rate.
    // @Units: Hz
    // @ReadOnly: True
    // @User: Standard
    {"TX_PKT_HZ", hasRadio, getPacketHz, nullptr, nullptr},
    // @Param: TX_TLM_RATIO
    // @DisplayName: Telemetry ratio
    // @Description: Share of packets used for telemetry from the receiver. Fixed at 1:2 in MAVLink link mode.
    // @Values: 0:Std,1:Off,2:1/128,3:1/64,4:1/32,5:1/16,6:1/8,7:1/4,8:1/2,9:Race
    // @User: Advanced
    {"TX_TLM_RATIO", hasRadio, getTlmRatio, setTlmRatio, lockTlmRatio},
    // @Param: TX_SWITCH_MODE
    // @DisplayName: Switch mode
    // @Description: How the AUX channels are sent. 4-channel rates: 0 Wide, 1 Hybrid. Full rates: 0 8ch, 1 16ch Rate/2, 2 12ch Mixed. Fixed at Hybrid / 16ch Rate/2 in MAVLink link mode.
    // @Values: 0:Wide / 8ch,1:Hybrid / 16ch Rate/2,2:12ch Mixed
    // @User: Advanced
    {"TX_SWITCH_MODE", hasSwitchMode, getSwitchMode, setSwitchMode, lockSwitchMode},
    // @Param: TX_ANT_MODE
    // @DisplayName: Antenna mode
    // @Description: How the TX uses its two radios. Dual band (X-Band) rates always use Gemini. The receiver follows this setting.
    // @Values: 0:Gemini,1:Antenna 1,2:Antenna 2,3:Switch
    // @Hardware: TX with two radios only
    // @User: Advanced
    {"TX_ANT_MODE", hasAntennaMode, getAntennaMode, setAntennaMode, nullptr},
    // @Param: TX_LINK_MODE
    // @DisplayName: Link mode
    // @Description: Normal carries RC and CRSF telemetry; MAVLink carries a MAVLink link to the GCS. Setting Normal ends this MAVLink session and the receiver changes to CRSF. At boot the TX returns to MAVLink if a GCS is sending MAVLink to it before a handset connects.
    // @Values: 0:Normal,1:MAVLink
    // @User: Standard
    {"TX_LINK_MODE", hasRadio, getLinkMode, setLinkMode, nullptr},
    // @Param: TX_POWER
    // @DisplayName: Max power
    // @Description: Maximum TX output power. With dynamic power on, the TX lowers its power below this when the link allows.
    // @Values: 10:10 mW,25:25 mW,50:50 mW,100:100 mW,250:250 mW,500:500 mW,1000:1000 mW,2000:2000 mW
    // @Units: mW
    // @Hardware: Each TX supports a range of these levels
    // @User: Standard
    {"TX_POWER", hasRadio, getPower, setPower, nullptr},
    // @Param: TX_DYN_POWER
    // @DisplayName: Dynamic power
    // @Description: Off holds the max power. Dyn adjusts the power to the link quality. AUX9-AUX12 adjust it too, and boost to max power while that channel is high.
    // @Values: 0:Off,1:Dyn,2:AUX9,3:AUX10,4:AUX11,5:AUX12
    // @User: Standard
    {"TX_DYN_POWER", hasRadio, getDynamicPower, setDynamicPower, nullptr},
    // @Param: TX_FAN_THRESH
    // @DisplayName: Fan threshold
    // @Description: Power level at which the TX turns its fan on.
    // @Values: 0:10 mW,1:25 mW,2:50 mW,3:100 mW,4:250 mW,5:500 mW,6:1000 mW,7:2000 mW,8:Never
    // @Hardware: TX with a fan only
    // @User: Advanced
    {"TX_FAN_THRESH", hasFan, getFanThreshold, setFanThreshold, nullptr},
#if defined(PLATFORM_ESP32)
    // @Param: TX_BP_TLM
    // @DisplayName: Backpack telemetry
    // @Description: How the TX backpack forwards telemetry. Off also cuts a GCS that is connected through the backpack.
    // @Values: 0:Off,1:ESPNOW,2:WiFi
    // @Hardware: ESP32 TX with a backpack enabled only
    // @User: Advanced
    {"TX_BP_TLM", hasBackpack, getBackpackTelemetry, setBackpackTelemetry, nullptr},
#endif
    // @Param: TX_VEH_SYSID
    // @DisplayName: Vehicle system ID
    // @Description: System ID of the vehicle the TX has joined, taken from the flight controller's heartbeat. 0 until one has been seen.
    // @ReadOnly: True
    // @User: Advanced
    {"TX_VEH_SYSID", nullptr, getVehicleSysid, nullptr, nullptr},
};

// Built from the link statistics the TX already has; nothing extra is requested from the receiver

static uint32_t lastLinkStats;
static uint32_t lastLinkInformation;
static mavlink_mlrs_radio_link_information_t sentInformation;

static const int8_t powerLevelsDbm[PWR_COUNT] = {10, 14, 17, 20, 24, 27, 30, 33};

// Short rate names, as the Lua's, for MLRS_RADIO_LINK_INFORMATION.mode_str (6 characters at most)
static const char *rateName(uint8_t enumRate)
{
    switch (enumRate)
    {
    case RATE_LORA_900_25HZ: case RATE_LORA_2G4_25HZ: return "25Hz";
    case RATE_LORA_900_50HZ: case RATE_LORA_2G4_50HZ: return "50Hz";
    case RATE_LORA_900_100HZ: case RATE_LORA_2G4_100HZ: return "100Hz";
    case RATE_LORA_900_100HZ_8CH: case RATE_LORA_2G4_100HZ_8CH: case RATE_LORA_DUAL_100HZ_8CH: return "100HzF";
    case RATE_LORA_900_150HZ: case RATE_LORA_2G4_150HZ: case RATE_LORA_DUAL_150HZ: return "150Hz";
    case RATE_LORA_900_200HZ: case RATE_LORA_2G4_200HZ: return "200Hz";
    case RATE_LORA_900_200HZ_8CH: case RATE_LORA_2G4_200HZ_8CH: return "200HzF";
    case RATE_LORA_900_250HZ: case RATE_LORA_2G4_250HZ: return "250Hz";
    case RATE_LORA_900_333HZ_8CH: case RATE_LORA_2G4_333HZ_8CH: return "333HzF";
    case RATE_LORA_900_500HZ: case RATE_LORA_2G4_500HZ: return "500Hz";
    case RATE_LORA_900_50HZ_DVDA: return "D50Hz";
    case RATE_FSK_900_1000HZ_8CH: return "K1000F";
    case RATE_FLRC_2G4_250HZ_DVDA: return "D250";
    case RATE_FLRC_2G4_500HZ_DVDA: return "D500";
    case RATE_FLRC_2G4_500HZ: return "F500";
    case RATE_FLRC_2G4_1000HZ: return "F1000";
    case RATE_FSK_2G4_250HZ_DVDA: return "DK250";
    case RATE_FSK_2G4_500HZ_DVDA: return "DK500";
    case RATE_FSK_2G4_1000HZ: return "K1000";
    default: return "";
    }
}

// RSSI as MLRS wants it with MLRS_FLAG_RSSI_DBM: 1..254 for -1..-254 dBm, 0 for no reception
static uint8_t rssiMagnitude(int8_t dbm)
{
    return dbm < 0 ? (uint8_t)(-dbm) : 0;
}

static void sendLinkStats()
{
    const bool linked = connectionState == connected;
    mavlink_mlrs_radio_link_stats_t stats = {};
    stats.flags = MLRS_FLAG_RSSI_DBM;
    if (linkStats.active_antenna)
        stats.flags |= MLRS_FLAG_RX_RECEIVE_ANTENNA2;
    if (!isDualRadio() || config.GetAntennaMode() != TX_RADIO_MODE_ANT_2)
        stats.flags |= MLRS_FLAG_TX_TRANSMIT_ANTENNA1;
    if (isDualRadio() && config.GetAntennaMode() != TX_RADIO_MODE_ANT_1)
        stats.flags |= MLRS_FLAG_TX_TRANSMIT_ANTENNA2;
    // There is one LQ for the uplink; the MAVLink stream's own LQ is not measured
    stats.rx_LQ_rc = linked ? linkStats.uplink_Link_quality : 0;
    stats.rx_LQ_ser = UINT8_MAX;
    stats.rx_rssi1 = linked ? rssiMagnitude((int8_t)linkStats.uplink_RSSI_1) : 0;
    // A receiver with one antenna never reports the second
    stats.rx_rssi2 = !linked ? 0 : (linkStats.uplink_RSSI_2 == 0 ? UINT8_MAX : rssiMagnitude((int8_t)linkStats.uplink_RSSI_2));
    stats.rx_snr1 = linked ? linkStats.uplink_SNR : INT8_MAX;
    stats.rx_snr2 = INT8_MAX;
    // The receiver's telemetry packets carry the MAVLink downlink
    stats.tx_LQ_ser = linked ? linkStats.downlink_Link_quality : 0;
    stats.tx_rssi1 = linked ? rssiMagnitude((int8_t)linkStats.downlink_RSSI_1) : 0;
    stats.tx_rssi2 = !linked ? 0 : (isDualRadio() ? rssiMagnitude((int8_t)linkStats.downlink_RSSI_2) : UINT8_MAX);
    stats.tx_snr1 = linked ? linkStats.downlink_SNR : INT8_MAX;
    stats.tx_snr2 = INT8_MAX;
    mavlink_message_t msg;
    mavlink_msg_mlrs_radio_link_stats_encode(0, 0, &msg, &stats);
    server.sendAsComponent(&msg, MAVLINK_MSG_ID_MLRS_RADIO_LINK_STATS_MIN_LEN, MAVLINK_MSG_ID_MLRS_RADIO_LINK_STATS_CRC);
}

static void buildLinkInformation(mavlink_mlrs_radio_link_information_t *info)
{
    const expresslrs_mod_settings_s *modParams = ExpressLRS_currAirRate_Modparams;
    const uint16_t frameRate = (1000000 + modParams->interval / 2) / modParams->interval;
    memset(info, 0, sizeof(*info));
    info->type = MLRS_LINK_TYPE_EXPRESSLRS;
    info->mode = modParams->enum_rate;
    info->tx_power = powerLevelsDbm[POWERMGNT::currPower()];
    // The receiver's telemetry power is not part of its link statistics
    info->rx_power = INT8_MAX;
    info->tx_frame_rate = frameRate;
    info->rx_frame_rate = ExpressLRS_currTlmDenom > 1 ? frameRate / ExpressLRS_currTlmDenom : 0;
    strncpy(info->mode_str, rateName(modParams->enum_rate), sizeof(info->mode_str));
    strncpy(info->band_str, modParams->radio_type == RADIO_TYPE_LR1121_LORA_DUAL ? "X-Band" : FHSSgetRegulatoryDomain(), sizeof(info->band_str));
    // Both ends run the same rate, so the rate table's sensitivity applies to both
    const int16_t sensitivity = get_elrs_RFperfParams(modParams->index)->RXsensitivity;
    info->tx_receive_sensitivity = info->rx_receive_sensitivity = sensitivity < 0 && sensitivity > -256 ? -sensitivity : 0;
}

static void sendLinkInformation(const mavlink_mlrs_radio_link_information_t *info)
{
    mavlink_message_t msg;
    mavlink_msg_mlrs_radio_link_information_encode(0, 0, &msg, info);
    if (server.sendAsComponent(&msg, MAVLINK_MSG_ID_MLRS_RADIO_LINK_INFORMATION_MIN_LEN, MAVLINK_MSG_ID_MLRS_RADIO_LINK_INFORMATION_CRC))
    {
        sentInformation = *info;
    }
}

static void updateLinkReports(uint32_t now)
{
    // Only once the TX knows the vehicle's system ID, so the GCS files them under the vehicle
    if (!server.ready() || now - lastLinkStats < firmwareOptions.tlm_report_interval)
        return;
    lastLinkStats = now;
    sendLinkStats();

    mavlink_mlrs_radio_link_information_t info;
    buildLinkInformation(&info);
    if (now - lastLinkInformation >= LINK_INFORMATION_INTERVAL || memcmp(&info, &sentInformation, sizeof(info)) != 0)
    {
        lastLinkInformation = now;
        sendLinkInformation(&info);
    }
}

#if defined(PLATFORM_ESP32)
static bool backpackGetsMavlink()
{
    // Same conditions as sendMAVLinkTelemetryToBackpack()
    return BackpackOrLogStrm != TxUSB && !config.GetBackpackDisable() && config.GetBackpackTlmMode() != BACKPACK_TELEM_MODE_OFF;
}
#endif

static void writeToGcs(const uint8_t *data, uint16_t size)
{
    TxUSB->write(data, size);
#if defined(PLATFORM_STM32)
    MavlinkUdp_Send(data, size);
#endif
#if defined(PLATFORM_ESP32)
    if (backpackGetsMavlink())
    {
        BackpackOrLogStrm->write(data, size);
    }
#endif
}

static bool queueFrame(const uint8_t *frame, uint16_t len)
{
    if (queuedLen + len > sizeof(queuedFrames))
        return false;
    memcpy(queuedFrames + queuedLen, frame, len);
    queuedLen += len;
    return true;
}

static void flushQueuedFrames()
{
    // Only between frames from the vehicle, so the TX's frames are not spliced into the middle of one
    if (queuedLen != 0 && vehicleRxStatus.parse_state <= MAVLINK_PARSE_STATE_IDLE)
    {
        writeToGcs(queuedFrames, queuedLen);
        queuedLen = 0;
    }
}

static uint8_t fallbackSysid() { return 1; }

static void start(uint32_t now)
{
    if (started)
        return;
    started = true;
    MavParamServer::Config cfg = {};
    cfg.compid = TLRS_MAV_TX_COMPID;
    cfg.fallbackSysid = fallbackSysid;
    cfg.heartbeatWaitMs = HEARTBEAT_WAIT;
    cfg.replyDelayMs = PARAM_REPLY_DELAY;
    cfg.maxFramesPerTick = 4;
    cfg.swVersion = MavParamServer::versionFromString(version);
    server.begin(params, sizeof(params) / sizeof(params[0]), cfg, queueFrame, now);
}

void TxMavlink_ProcessFromGcs(txMavlinkGcsLink_e link, const uint8_t *data, uint16_t size)
{
    const uint32_t now = millis();
    start(now);
    for (uint16_t i = 0; i < size; i++)
    {
        mavlink_message_t msg;
        mavlink_status_t status;
        if (mavlink_frame_char_buffer(&gcsRxMsg[link], &gcsRxStatus[link], data[i], &msg, &status) == MAVLINK_FRAMING_OK)
        {
            server.handleGcsMessage(&msg, now);
        }
    }
}

void TxMavlink_ForwardToGcs(const uint8_t *data, uint16_t size)
{
    // Frames arrive over the air in chunks that are not aligned to frame boundaries,
    // so write out whole runs of bytes and slot the TX's frames in where a frame ends
    uint16_t begin = 0;
    for (uint16_t i = 0; i < size; i++)
    {
        mavlink_message_t msg;
        mavlink_status_t status;
        if (mavlink_frame_char_buffer(&vehicleRxMsg, &vehicleRxStatus, data[i], &msg, &status) == MAVLINK_FRAMING_OK)
        {
            server.handleVehicleMessage(&msg);
        }
        if (queuedLen != 0 && vehicleRxStatus.parse_state <= MAVLINK_PARSE_STATE_IDLE)
        {
            writeToGcs(data + begin, i + 1 - begin);
            begin = i + 1;
            flushQueuedFrames();
        }
    }
    if (begin < size)
    {
        writeToGcs(data + begin, size - begin);
    }
    lastVehicleByte = millis();
}

void TxMavlink_Update(uint32_t now)
{
    start(now);

    if (vehicleRxStatus.parse_state > MAVLINK_PARSE_STATE_IDLE && now - lastVehicleByte > DOWNLINK_FRAME_TIMEOUT)
    {
        // The rest of the frame is never coming, the GCS will discard what it has as a bad frame
        vehicleRxStatus.parse_state = MAVLINK_PARSE_STATE_IDLE;
    }

    server.tick(now);
    updateLinkReports(now);
    flushQueuedFrames();
}
